version: "3.9"

services:
  api_server:
    build:
      context: ./app_V2
      dockerfile: Dockerfile.app
    ports:
      - "8005:8000"
    networks:
      - network_rakuten
    volumes:
      - ./app_V2:/app
      - ./BDD:/BDD
      - ./models:/models

  test_ci:
    build:
      context: ./test_ci
      dockerfile: Dockerfile.test_ci
    networks:
      - network_rakuten
    volumes:
      - ./test_ci:/test_ci
      - ./app_V2:/app                      # AJOUT
      - ./models:/models                   # AJOUT
    depends_on:
      - api_server

##############################################################
# Ajout de networks
networks:
  network_rakuten:
##############################################################
