name: test_ci

on:
  push:
    branches:
      - main  

jobs:
  test_ci:
    runs-on: [ubuntu-22.04, ubuntu-latest]  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # version de Python 

      - name: Display directory contents
        run: ls -R  # pour déboguer le contenu du répertoire


      - name: Install dependencies
        run: |
          pip install -r test_ci/requirements.txt  

      - name: Run tests
        run: |
          cd test_ci
          ./run_tests.sh
