name: Test CI

on:
  push:
    branches:
      - main

jobs:
  test_ci:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        #######################################################
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

        #######################################################
      - name: Install Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Start Docker Compose services
        run: docker-compose -f ./docker-compose.yml up -d

      - name: Show Docker Compose processes
        run: docker-compose ps
  
      - name: Show Docker Compose logs
        run: docker-compose logs

      - name: Show test service logs
        run: docker-compose logs test_ci

      - name: Install dependencies
        run: |
          cd test_ci
          pip install -r requirements.txt
##############################
      - name: Run tests
        #run: docker-compose exec test_ci /test_ci/run_tests.sh
        run: |
          cd test_ci
          ./run_tests.sh



#      - name: Run tests
#        #run: ./run_tests.sh
#        run: test_ci/run_tests.sh



#      - name: Expose application on port 8005
#        run: python -m http.server 8005 &
#        env:
#          Test CI: true